module

public import MaximumModulus

public section

#check MaximumModulus.AllRadiiStatement
#check @MaximumModulus.allRadiiStatement
#check @MaximumModulus.bounded_maxPoints_at_arbitrarily_large_radii
#check @MaximumModulus.all_radii_growth_impossible
#print MaximumModulus.allRadiiStatement
#print MaximumModulus.bounded_maxPoints_at_arbitrarily_large_radii
#print MaximumModulus.all_radii_growth_impossible
#print axioms MaximumModulus.allRadiiStatement
#print axioms MaximumModulus.bounded_maxPoints_at_arbitrarily_large_radii
#print axioms MaximumModulus.all_radii_growth_impossible
#print axioms MaximumModulus.regularLogDerivativeHighCount_open_closure_projection
#print axioms MaximumModulus.regularLogDerivativeHighCount_empty
#print axioms MaximumModulus.omittedHighCountBranchCover_exists
#print axioms MaximumModulus.OmittedHighCountBranchCover.actual_closure_branches
#print axioms MaximumModulus.regular_high_count_closure_omitted_local_projection_isOpen
#print axioms MaximumModulus.InfinityTargetBranchCover.product_germ_nonconstant
#print axioms MaximumModulus.InfinityTargetBranchCover.high_count_selected_sandwich
#print axioms MaximumModulus.regularLogDerivativeHighCount_open_local_projection_at_infinity
#print MaximumModulus.Entire
#print MaximumModulus.IsMonomial
#print MaximumModulus.MaxPoints
#print MaximumModulus.GoodRadius
#print MaximumModulus.CofinalBound
#print MaximumModulus.AllRadiiStatement
#print MaximumModulus.AlmostEverywhereBoundStatement
#print MaximumModulus.finite_maxPoints
#print MaximumModulus.cofinalBound_of_ae_ncard
#print MaximumModulus.almostEverywhereStatement_implies_allRadiiStatement
#print MaximumModulus.allRadiiStatement_implies_negative
#print MaximumModulus.StatementAudit.OriginalRequiredStatement

#print axioms MaximumModulus.maxPoints_nonempty
#print axioms MaximumModulus.closure_continues_through_finite_imageBranches
#print axioms MaximumModulus.finite_imageBranches_local_projection_isOpen
#print axioms MaximumModulus.finiteValueEmbedding_preimage_closure
#print axioms MaximumModulus.logarithmic_pair_product_germ_nonconstant
#print axioms MaximumModulus.finiteTargetBranchCover_exists
#print axioms MaximumModulus.FiniteTargetBranchCover.regular_at_punctured_branch
#print axioms MaximumModulus.FiniteTargetBranchCover.physical_count_radius
#print axioms MaximumModulus.finiteSingularTargets_locally_finite
#print axioms MaximumModulus.finiteSingularTargets_countable
#print axioms MaximumModulus.finiteSingularSquareRadii_countable
#print axioms MaximumModulus.positiveProductFiberBound_of_regular_high_count_empty
#print axioms MaximumModulus.logDerivative_high_count_omitted_finite_image_cover
#print axioms MaximumModulus.FiniteTargetBranchCover.central_fiber_count_le_branch
#print axioms MaximumModulus.FiniteTargetBranchCover.high_count_selected_sandwich
#print axioms MaximumModulus.finite_regular_high_count_closure_contains_analytic_branch
#print axioms MaximumModulus.regular_high_count_closure_finite_local_projection_isOpen
#print axioms MaximumModulus.infinityValueEmbedding_preimage_closure
#print axioms MaximumModulus.infinityTargetBranchCover_exists
#print axioms MaximumModulus.regularLogDerivativeHighCount_closure_product_ne_zero
#print axioms MaximumModulus.maxPoints_eq_norm_level
#print axioms MaximumModulus.entire_reflection
#print axioms MaximumModulus.analyticOnNhd_reflectionProduct
#print axioms MaximumModulus.reflectionProduct_eq_sq_norm
#print axioms MaximumModulus.reflectionProduct_constant_of_infinite_maxPoints
#print axioms MaximumModulus.entire_factor_at_zero
#print axioms MaximumModulus.eq_zero_value_of_reflectionProduct_constant
#print axioms MaximumModulus.isMonomial_of_reflectionProduct_constant
#print axioms MaximumModulus.finite_maxPoints
#print axioms MaximumModulus.cofinalBound_not_growth
#print axioms MaximumModulus.cofinalBound_not_tendsto
#print axioms MaximumModulus.cofinalBound_of_ae
#print axioms MaximumModulus.cofinalBound_of_locallyFinite_exceptions
#print axioms MaximumModulus.allRadiiStatement_implies_negative
#print axioms MaximumModulus.cofinalBound_of_ae_ncard
#print axioms MaximumModulus.almostEverywhereStatement_implies_allRadiiStatement
#print axioms MaximumModulus.small_inverse_pairs_finite_ncard_le
#print axioms MaximumModulus.inverse_pairs_eq_small_of_norm_lt_sq
#print axioms MaximumModulus.inverse_pairs_finite_ncard_le_of_norm_lt_sq
#print MaximumModulus.analytic_local_valence
#print axioms MaximumModulus.power_fiber_finite_ncard_le
#print axioms MaximumModulus.analytic_germ_root
#print axioms MaximumModulus.local_power_coordinate_valence
#print axioms MaximumModulus.analytic_local_valence
#print axioms MaximumModulus.maxPoints_mapsTo_inversePairs
#print axioms MaximumModulus.maxPoints_finite_ncard_le_inversePairs
#print axioms MaximumModulus.StatementAudit.statement_correspondence
#print axioms MaximumModulus.StatementAudit.original_finiteness

#print MaximumModulus.PositiveProductFiberBound
#print MaximumModulus.cofinalBound_of_positiveProductFiberBound
#print MaximumModulus.normalizedLogDerivative_small_product_bound
#print MaximumModulus.exists_positive_envelope_derivative_off_countable
#print axioms MaximumModulus.imageBranch_fibers_radius
#print axioms MaximumModulus.finite_imageBranch_comparisons_radius
#print axioms MaximumModulus.analytic_inverseRoot_chart
#print axioms MaximumModulus.analytic_inverseRoot_capture
#print axioms MaximumModulus.analytic_inverseRoot_family
#print axioms MaximumModulus.analytic_inverseRoot_pair_family
#print axioms MaximumModulus.analytic_inverseRoot_local_fiber_count
#print axioms MaximumModulus.weightedLogDerivative_factor
#print axioms MaximumModulus.normalizedLogDerivative_finite_order
#print axioms MaximumModulus.normalizedLogDerivative_no_reciprocal_symmetry
#print axioms MaximumModulus.normalizedLogDerivative_small_product_bound
#print axioms MaximumModulus.no_local_normalized_reciprocity
#print axioms MaximumModulus.continuous_sphereLogDerivative
#print axioms MaximumModulus.normalizedLogDerivative_finite_inverse_pairs
#print axioms MaximumModulus.compact_sphereLogDerivative_inverse_image
#print axioms MaximumModulus.isProperMap_sphereCorrespondenceMap
#print axioms MaximumModulus.sphereCorrespondenceMap_finite_fiber
#print axioms MaximumModulus.angular_stationarity
#print axioms MaximumModulus.value_ne_zero_of_maxPoint
#print axioms MaximumModulus.common_logarithmic_derivative_at_maxPoints
#print axioms MaximumModulus.actual_maxPoints_mapsTo_inversePairs
#print axioms MaximumModulus.squaredMaximum_strictMonoOn
#print axioms MaximumModulus.squaredMaximum_lipschitzOn_Icc
#print axioms MaximumModulus.exists_positive_envelope_derivative_off_countable
#print axioms MaximumModulus.cofinalBound_of_positiveProductFiberBound
#print axioms MaximumModulus.bad_locus_empty_of_open_closure_projection
#print axioms MaximumModulus.analytic_imageBranch_locally_closed
#print axioms MaximumModulus.imageBranch_full_branch_of_clopen_membership
#print axioms MaximumModulus.isOpen_product_projection_of_analytic_charts
#print axioms MaximumModulus.compact_fiber_capture
#print axioms MaximumModulus.closedMap_fiber_capture
#print axioms MaximumModulus.normalizedLogDerivative_finite_order_regular
#print axioms MaximumModulus.reciprocalSphereLogDerivative_pole_germ
#print axioms MaximumModulus.sphereLogDerivative_pole_inverse_chart
#print axioms MaximumModulus.sphereLogDerivative_regular_inverse_chart
#print axioms MaximumModulus.finite_entire_zeros_in_compact_of_ne_zero
#print axioms MaximumModulus.finite_sphereLogDerivative_omitted_roots_in_compact
#print axioms MaximumModulus.sphereLogDerivative_small_product_bound
#print axioms MaximumModulus.imageBranch_noncentral_image_is_graph
#print axioms MaximumModulus.selected_imageBranches_punctured_closure
#print axioms MaximumModulus.imageBranch_full_branch_of_captured_subbranches
#print axioms MaximumModulus.closure_of_local_selected_imageBranches
#print axioms MaximumModulus.local_selected_imageBranches_closure_projection_isOpen
#print axioms MaximumModulus.logDerivative_high_count_has_bounded_survivor
#print axioms MaximumModulus.logDerivative_high_count_omitted_value_capture
#print axioms MaximumModulus.finite_omitted_roots_in_coordinate_annulus
#print axioms MaximumModulus.imageBranches_eq_or_disjoint_of_stable_comparisons
#print axioms MaximumModulus.finite_imageBranches_noncentral_image_is_graph
#print axioms MaximumModulus.inverseRoot_branch_germ_nonconstant
#print axioms MaximumModulus.no_constant_product_regular_pair_germ
#print axioms MaximumModulus.no_constant_product_spherical_regular_pair_germ
#print axioms MaximumModulus.sphereCorrespondence_regular_chart_capture
#print axioms MaximumModulus.finite_orders_common_power
#print axioms MaximumModulus.RegularSpherePairChart.capture_rootPair
#print axioms MaximumModulus.sphereCorrespondence_regular_root_capture
#print axioms MaximumModulus.RegularSpherePairChart.rootPair_values_radius
#print axioms MaximumModulus.regularSphereRootFamily_values_radius
#print axioms MaximumModulus.regularSphereRootPair_analytic
#print axioms MaximumModulus.sphereCorrespondence_regular_finite_family
#print axioms MaximumModulus.countable_exceptional_sphere_targets
#print axioms MaximumModulus.countable_exceptional_sphere_radii
#print MaximumModulus.RegularLogDerivativeHighCount
#print axioms MaximumModulus.regularLogDerivativeHighCount_closure_avoids_small_products
#print axioms MaximumModulus.regularLogDerivativeHighCount_empty_of_open_closure_projection
#print axioms MaximumModulus.sphere_inversePairs_eq_normalized
#print axioms MaximumModulus.normalized_inversePairs_bound_at_regular_target
#print axioms MaximumModulus.finite_analytic_physical_inversePairs_count_radius
#print axioms MaximumModulus.productGermClass_eq_univ_of_total_graph
#print axioms MaximumModulus.central_fiber_count_le_of_total_graph
